/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ro'yxatdan o'tish
     * @description Create an account. The new user always receives exactly the CUSTOMER role.
     */
    post: operations["register_api_v1_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Tizimga kirish */
    post: operations["login_api_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/otp/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Tasdiqlash kodini so'rash */
    post: operations["request_otp_api_v1_auth_otp_request_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/otp/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Kodni tasdiqlash */
    post: operations["verify_otp_api_v1_auth_otp_verify_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Tokenni yangilash */
    post: operations["refresh_api_v1_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Chiqish */
    post: operations["logout_api_v1_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout-all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Barcha qurilmalardan chiqish */
    post: operations["logout_all_api_v1_auth_logout_all_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/password/forgot": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Parolni tiklash kodini so'rash
     * @description Always reports success, so the endpoint cannot be used to enumerate accounts.
     */
    post: operations["password_forgot_api_v1_auth_password_forgot_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/password/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Parolni tiklash */
    post: operations["password_reset_api_v1_auth_password_reset_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/password/change": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Parolni o'zgartirish */
    post: operations["password_change_api_v1_auth_password_change_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Joriy foydalanuvchi */
    get: operations["me_api_v1_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/vehicles/brands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Markalar ro'yxati */
    get: operations["list_brands_api_v1_vehicles_brands_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/vehicles/brands/{brand_slug}/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Marka modellari */
    get: operations["list_models_api_v1_vehicles_brands__brand_slug__models_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/vehicles/models/{model_id}/generations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Model avlodlari */
    get: operations["list_generations_api_v1_vehicles_models__model_id__generations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/vehicles/models/{model_id}/years": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Model yillari */
    get: operations["list_years_api_v1_vehicles_models__model_id__years_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/vehicles/models/{model_id}/variants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Variantlar */
    get: operations["list_variants_api_v1_vehicles_models__model_id__variants_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/vehicles/engines": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Dvigatellar */
    get: operations["list_engines_api_v1_vehicles_engines_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/garage/vehicles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Mening avtomobillarim */
    get: operations["list_vehicles_api_v1_garage_vehicles_get"];
    put?: never;
    /** Avtomobil qo'shish */
    post: operations["add_vehicle_api_v1_garage_vehicles_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/garage/vehicles/{vehicle_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Avtomobil */
    get: operations["get_vehicle_api_v1_garage_vehicles__vehicle_id__get"];
    put?: never;
    post?: never;
    /** Avtomobilni o'chirish */
    delete: operations["delete_vehicle_api_v1_garage_vehicles__vehicle_id__delete"];
    options?: never;
    head?: never;
    /** Avtomobilni tahrirlash */
    patch: operations["update_vehicle_api_v1_garage_vehicles__vehicle_id__patch"];
    trace?: never;
  };
  "/api/v1/garage/vehicles/{vehicle_id}/primary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Asosiy avtomobil qilish */
    post: operations["set_primary_api_v1_garage_vehicles__vehicle_id__primary_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Kategoriyalar
     * @description Categories with live product counts, so the UI never shows an empty chip.
     */
    get: operations["list_categories_api_v1_catalog_categories_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/brands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detal brendlari */
    get: operations["list_part_brands_api_v1_catalog_brands_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Marketplace qidiruvi */
    get: operations["search_products_api_v1_products_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/suggest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Qidiruv takliflari */
    get: operations["suggest_api_v1_products_suggest_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Mahsulot sahifasi */
    get: operations["product_detail_api_v1_products__slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/compatibility/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Bitta mahsulot mosligini tekshirish */
    get: operations["check_api_v1_compatibility_check_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/compatibility/check-bulk": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ro'yxat uchun moslikni tekshirish */
    post: operations["check_bulk_api_v1_compatibility_check_bulk_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/compatibility/claims": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Katalog mosligini kiritish (faqat katalog menejeri)
     * @description A catalogue manager's claim is recorded as OEM_CATALOG and marked verified.
     */
    put: operations["upsert_claim_api_v1_compatibility_claims_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cart": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Savat */
    get: operations["view_cart_api_v1_cart_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cart/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Savatga qo'shish */
    post: operations["add_item_api_v1_cart_items_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cart/items/{item_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Savatdan o'chirish */
    delete: operations["remove_item_api_v1_cart_items__item_id__delete"];
    options?: never;
    head?: never;
    /** Sonini o'zgartirish */
    patch: operations["set_quantity_api_v1_cart_items__item_id__patch"];
    trace?: never;
  };
  "/api/v1/cart/merge": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mehmon savatini birlashtirish
     * @description Call once right after login so nothing the guest picked is lost.
     */
    post: operations["merge_api_v1_cart_merge_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/orders/checkout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Buyurtma rasmiylashtirish
     * @description Prices, delivery and totals are all computed here from live offers.
     *     Stock is reserved inside the same transaction, so the cart cannot oversell.
     */
    post: operations["checkout_api_v1_orders_checkout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Mening buyurtmalarim */
    get: operations["my_orders_api_v1_orders_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/orders/{order_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Buyurtma */
    get: operations["get_order_api_v1_orders__order_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/orders/{order_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Buyurtmani bekor qilish
     * @description A buyer may cancel their own order, and only while it has not shipped.
     */
    post: operations["cancel_order_api_v1_orders__order_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/payments/callback/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * To'lov tizimi callback'i
     * @description Gateway-facing endpoint. The signature is verified inside the adapter;
     *     an unsigned or mis-signed callback never moves an order.
     */
    post: operations["payment_callback_api_v1_payments_callback__provider__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/seller/{seller_id}/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Do'kon buyurtmalari */
    get: operations["seller_orders_api_v1_seller__seller_id__orders_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/seller/{seller_id}/orders/{order_id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Holatni yangilash */
    post: operations["seller_change_status_api_v1_seller__seller_id__orders__order_id__status_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sellers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sotuvchilar */
    get: operations["list_sellers_api_v1_sellers_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sellers/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Mening do'konlarim */
    get: operations["my_stores_api_v1_sellers_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sellers/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Do'kon sahifasi */
    get: operations["seller_detail_api_v1_sellers__slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sellers/onboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sotuvchi bo'lish
     * @description Creates a PENDING store and grants the SELLER role. Selling needs admin approval.
     */
    post: operations["onboard_api_v1_sellers_onboard_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sellers/{seller_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Do'kon profilini tahrirlash */
    patch: operations["update_store_api_v1_sellers__seller_id__patch"];
    trace?: never;
  };
  "/api/v1/sellers/{seller_id}/verification": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Tasdiqlash so'rovi yuborish */
    post: operations["request_verification_api_v1_sellers__seller_id__verification_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sellers/verification/{request_id}/decide": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Tasdiqlash qarori (faqat administrator) */
    post: operations["decide_verification_api_v1_sellers_verification__request_id__decide_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/seller/{seller_id}/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mahsulot yaratish */
    post: operations["create_product_api_v1_seller__seller_id__products_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/seller/products/{product_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Mahsulotni tahrirlash */
    patch: operations["update_product_api_v1_seller_products__product_id__patch"];
    trace?: never;
  };
  "/api/v1/seller/{seller_id}/offers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Narx va qoldiqni belgilash */
    put: operations["upsert_offer_api_v1_seller__seller_id__offers_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations["ready_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AddressIn */
    AddressIn: {
      /** Recipient Name */
      recipient_name: string;
      /** Phone */
      phone: string;
      /** Region */
      region: string;
      /** District */
      district: string;
      /** Street */
      street: string;
      /** Landmark */
      landmark?: string | null;
    };
    /** AuthResult */
    AuthResult: {
      user: components["schemas"]["UserOut"];
      tokens: components["schemas"]["TokenPair"];
    };
    /**
     * BodyType
     * @enum {string}
     */
    BodyType: "SEDAN" | "HATCHBACK" | "WAGON" | "SUV" | "MINIVAN" | "VAN" | "PICKUP" | "COUPE";
    /** BrandOut */
    BrandOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Logo Url */
      logo_url?: string | null;
      /**
       * Is Popular
       * @default false
       */
      is_popular: boolean;
    };
    /** CartItemIn */
    CartItemIn: {
      /**
       * Offer Id
       * Format: uuid
       */
      offer_id: string;
      /**
       * Quantity
       * @default 1
       */
      quantity: number;
    };
    /** CartItemQuantityIn */
    CartItemQuantityIn: {
      /** Quantity */
      quantity: number;
    };
    /** CartLineOut */
    CartLineOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Offer Id
       * Format: uuid
       */
      offer_id: string;
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /** Product Slug */
      product_slug: string;
      /** Name Uz */
      name_uz: string;
      /** Name Ru */
      name_ru?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Unit Price */
      unit_price: string;
      /** Quantity */
      quantity: number;
      /** Line Total */
      line_total: string;
      /** Available */
      available: number;
      /**
       * Over Stock
       * @default false
       */
      over_stock: boolean;
      seller: components["schemas"]["SellerBrief"];
      compatibility?: components["schemas"]["CompatibilityOut"] | null;
    };
    /** CartOut */
    CartOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Groups */
      groups: components["schemas"]["CartSellerGroup"][];
      /** Item Count */
      item_count: number;
      /** Subtotal */
      subtotal: string;
      /** Delivery Total */
      delivery_total: string;
      /** Discount Total */
      discount_total: string;
      /** Grand Total */
      grand_total: string;
      /**
       * Currency
       * @default UZS
       */
      currency: string;
      /**
       * Blocking Issues
       * @default []
       */
      blocking_issues: string[];
    };
    /**
     * CartSellerGroup
     * @description A cart spans sellers; each is delivered and priced on its own.
     */
    CartSellerGroup: {
      seller: components["schemas"]["SellerBrief"];
      /** Lines */
      lines: components["schemas"]["CartLineOut"][];
      /** Subtotal */
      subtotal: string;
      /** Delivery Fee */
      delivery_fee: string;
      /** Free Delivery Applied */
      free_delivery_applied: boolean;
      /** Total */
      total: string;
    };
    /** CategoryOut */
    CategoryOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Name Uz */
      name_uz: string;
      /** Name Ru */
      name_ru?: string | null;
      /** Name En */
      name_en?: string | null;
      /** Icon */
      icon?: string | null;
      /** Parent Id */
      parent_id?: string | null;
      /**
       * Product Count
       * @default 0
       */
      product_count: number;
    };
    /** CheckoutIn */
    CheckoutIn: {
      address: components["schemas"]["AddressIn"];
      /** @default CASH_ON_DELIVERY */
      payment_method: components["schemas"]["PaymentMethod"];
      /** @default COURIER_PARTNER */
      delivery_method: components["schemas"]["DeliveryMethod"];
      /** Comment */
      comment?: string | null;
      /** Return Url */
      return_url?: string | null;
    };
    /**
     * CompatSource
     * @description Ordered by trust. See ``SOURCE_PRIORITY``.
     * @enum {string}
     */
    CompatSource: "OEM_CATALOG" | "MANUFACTURER" | "STRUCTURED" | "SELLER" | "AI_INFERENCE";
    /**
     * CompatStatus
     * @enum {string}
     */
    CompatStatus: "COMPATIBLE" | "REQUIRES_VERIFICATION" | "NOT_COMPATIBLE";
    /** CompatibilityBulkQuery */
    CompatibilityBulkQuery: {
      /**
       * Variant Id
       * Format: uuid
       */
      variant_id: string;
      /** Product Ids */
      product_ids: string[];
    };
    /** CompatibilityClaimIn */
    CompatibilityClaimIn: {
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /**
       * Variant Id
       * Format: uuid
       */
      variant_id: string;
      status: components["schemas"]["CompatStatus"];
      /** Note Uz */
      note_uz?: string | null;
      /** Note Ru */
      note_ru?: string | null;
    };
    /**
     * CompatibilityOut
     * @description What the UI needs to render a fitment badge *and* say where it came from.
     */
    CompatibilityOut: {
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /**
       * Variant Id
       * Format: uuid
       */
      variant_id: string;
      status: components["schemas"]["CompatStatus"];
      source: components["schemas"]["CompatSource"];
      /** Confidence */
      confidence?: string | null;
      /**
       * Verified
       * @default false
       */
      verified: boolean;
      /** Note Uz */
      note_uz?: string | null;
      /** Note Ru */
      note_ru?: string | null;
      /** Source Ref */
      source_ref?: string | null;
    };
    /**
     * ContactChannel
     * @enum {string}
     */
    ContactChannel: "PHONE" | "EMAIL";
    /**
     * DeliveryMethod
     * @enum {string}
     */
    DeliveryMethod: "SELLER_DELIVERY" | "COURIER_PARTNER" | "STORE_PICKUP";
    /** EngineOut */
    EngineOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Code */
      code: string;
      /** Displacement L */
      displacement_l: string;
      fuel: components["schemas"]["FuelType"];
      /** Power Hp */
      power_hp?: number | null;
    };
    /**
     * FuelType
     * @enum {string}
     */
    FuelType: "PETROL" | "GAS" | "PETROL_GAS" | "DIESEL" | "HYBRID" | "ELECTRIC";
    /** GarageVehicleIn */
    GarageVehicleIn: {
      /**
       * Variant Id
       * Format: uuid
       */
      variant_id: string;
      /** Year */
      year: number;
      /** Nickname */
      nickname?: string | null;
      /** Plate Number */
      plate_number?: string | null;
      /** Color */
      color?: string | null;
      /** Vin */
      vin?: string | null;
      /** Mileage Km */
      mileage_km?: number | null;
      /** Next Service Km */
      next_service_km?: number | null;
      /** Purchased On */
      purchased_on?: string | null;
      /**
       * Make Primary
       * @default false
       */
      make_primary: boolean;
    };
    /** GarageVehicleOut */
    GarageVehicleOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Year */
      year: number;
      /** Nickname */
      nickname: string | null;
      /** Plate Number */
      plate_number: string | null;
      /** Color */
      color: string | null;
      /** Vin Masked */
      vin_masked?: string | null;
      /** Mileage Km */
      mileage_km: number | null;
      /** Next Service Km */
      next_service_km: number | null;
      /** Purchased On */
      purchased_on: string | null;
      /** Photo Url */
      photo_url: string | null;
      /** Is Primary */
      is_primary: boolean;
      variant: components["schemas"]["VariantOut"];
    };
    /** GarageVehicleUpdate */
    GarageVehicleUpdate: {
      /** Nickname */
      nickname?: string | null;
      /** Plate Number */
      plate_number?: string | null;
      /** Color */
      color?: string | null;
      /** Vin */
      vin?: string | null;
      /** Mileage Km */
      mileage_km?: number | null;
      /** Next Service Km */
      next_service_km?: number | null;
      /** Purchased On */
      purchased_on?: string | null;
    };
    /** GenerationOut */
    GenerationOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Model Id
       * Format: uuid
       */
      model_id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Year From */
      year_from: number;
      /** Year To */
      year_to?: number | null;
      body_type?: components["schemas"]["BodyType"] | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginIn */
    LoginIn: {
      /** Identifier */
      identifier: string;
      /** Password */
      password: string;
    };
    /** MediaOut */
    MediaOut: {
      /** Url */
      url: string;
      /** Thumbnail Url */
      thumbnail_url?: string | null;
      /** Alt Uz */
      alt_uz?: string | null;
    };
    /** ModelOut */
    ModelOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Brand Id
       * Format: uuid
       */
      brand_id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /**
       * Is Popular
       * @default false
       */
      is_popular: boolean;
    };
    /** OfferOut */
    OfferOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Price */
      price: string;
      /** Old Price */
      old_price?: string | null;
      /**
       * Currency
       * @default UZS
       */
      currency: string;
      /** Available */
      available: number;
      condition: components["schemas"]["ProductCondition"];
      /** Warranty Months */
      warranty_months?: number | null;
      /** Delivery Days */
      delivery_days?: number | null;
      /** Delivery Fee */
      delivery_fee?: string | null;
      status: components["schemas"]["OfferStatus"];
      seller: components["schemas"]["SellerBrief"];
      /** Discount Percent */
      readonly discount_percent: number | null;
    };
    /**
     * OfferStatus
     * @enum {string}
     */
    OfferStatus: "ACTIVE" | "PAUSED" | "OUT_OF_STOCK" | "ARCHIVED";
    /**
     * OfferUpsertIn
     * @description A seller's own price and stock. Never accepted from a buyer.
     */
    OfferUpsertIn: {
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /** Price */
      price: number | string;
      /** Old Price */
      old_price?: number | string | null;
      /** Stock */
      stock: number;
      /** @default NEW */
      condition: components["schemas"]["ProductCondition"];
      /** Warranty Months */
      warranty_months?: number | null;
      /** Delivery Days */
      delivery_days?: number | null;
      /** Delivery Fee */
      delivery_fee?: number | string | null;
      /** @default ACTIVE */
      status: components["schemas"]["OfferStatus"];
    };
    /** OrderEventOut */
    OrderEventOut: {
      from_status: components["schemas"]["OrderStatus"] | null;
      to_status: components["schemas"]["OrderStatus"];
      /** Note */
      note?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** OrderItemOut */
    OrderItemOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Product Id */
      product_id: string | null;
      /** Product Name */
      product_name: string;
      /** Product Slug */
      product_slug: string;
      /** Image Url */
      image_url?: string | null;
      /** Oem Number */
      oem_number?: string | null;
      /** Unit Price */
      unit_price: string;
      /** Quantity */
      quantity: number;
      /** Line Total */
      line_total: string;
    };
    /** OrderOut */
    OrderOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Number */
      number: string;
      status: components["schemas"]["OrderStatus"];
      /** Subtotal */
      subtotal: string;
      /** Delivery Total */
      delivery_total: string;
      /** Discount Total */
      discount_total: string;
      /** Grand Total */
      grand_total: string;
      /** Currency */
      currency: string;
      payment_method: components["schemas"]["PaymentMethod"];
      /** Recipient Name */
      recipient_name: string;
      /** Recipient Phone */
      recipient_phone: string;
      /** Address Snapshot */
      address_snapshot: {
        [key: string]: unknown;
      };
      /** Comment */
      comment?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Placed At */
      placed_at?: string | null;
      /** Completed At */
      completed_at?: string | null;
      /** Sub Orders */
      sub_orders: components["schemas"]["SubOrderOut"][];
      /**
       * Events
       * @default []
       */
      events: components["schemas"]["OrderEventOut"][];
      /** Payment Url */
      payment_url?: string | null;
    };
    /**
     * OrderStatus
     * @enum {string}
     */
    OrderStatus:
      | "PENDING"
      | "CONFIRMED"
      | "PREPARING"
      | "SHIPPED"
      | "DELIVERED"
      | "COMPLETED"
      | "CANCELLED"
      | "REFUNDED"
      | "DISPUTED";
    /**
     * OtpPurpose
     * @enum {string}
     */
    OtpPurpose: "REGISTER" | "LOGIN" | "VERIFY_CONTACT" | "PASSWORD_RESET";
    /** OtpRequestIn */
    OtpRequestIn: {
      channel: components["schemas"]["ContactChannel"];
      /** Destination */
      destination: string;
      /** @default VERIFY_CONTACT */
      purpose: components["schemas"]["OtpPurpose"];
    };
    /** OtpRequested */
    OtpRequested: {
      /**
       * Sent
       * @default true
       */
      sent: boolean;
      /**
       * Expires In
       * @default 300
       */
      expires_in: number;
      /** Debug Code */
      debug_code?: string | null;
    };
    /** OtpVerifyIn */
    OtpVerifyIn: {
      channel: components["schemas"]["ContactChannel"];
      /** Destination */
      destination: string;
      /** @default VERIFY_CONTACT */
      purpose: components["schemas"]["OtpPurpose"];
      /** Code */
      code: string;
    };
    /** Page[ProductListItem] */
    Page_ProductListItem_: {
      /** Items */
      items: components["schemas"]["ProductListItem"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Size */
      size: number;
      /** Pages */
      pages: number;
    };
    /** PartBrandOut */
    PartBrandOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Logo Url */
      logo_url?: string | null;
      /** Country */
      country?: string | null;
    };
    /** PasswordChangeIn */
    PasswordChangeIn: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /** PasswordForgotIn */
    PasswordForgotIn: {
      /** Identifier */
      identifier: string;
    };
    /** PasswordResetIn */
    PasswordResetIn: {
      /** Identifier */
      identifier: string;
      /** Code */
      code: string;
      /** New Password */
      new_password: string;
    };
    /**
     * PaymentMethod
     * @enum {string}
     */
    PaymentMethod: "CASH_ON_DELIVERY" | "CLICK" | "PAYME" | "UZCARD" | "HUMO" | "CARD" | "SANDBOX";
    /**
     * ProductCondition
     * @enum {string}
     */
    ProductCondition: "NEW" | "USED" | "REFURBISHED";
    /** ProductCreateIn */
    ProductCreateIn: {
      /** Name Uz */
      name_uz: string;
      /** Name Ru */
      name_ru?: string | null;
      /** Description Uz */
      description_uz?: string | null;
      /** Category Slug */
      category_slug: string;
      /** Part Brand Slug */
      part_brand_slug?: string | null;
      /** Oem Number */
      oem_number?: string | null;
      /**
       * Oem Alternates
       * @default []
       */
      oem_alternates: string[];
      /** Country Of Origin */
      country_of_origin?: string | null;
      /** Warranty Months */
      warranty_months?: number | null;
      /**
       * Specs
       * @default []
       */
      specs: components["schemas"]["SpecOut"][];
    };
    /** ProductDetail */
    ProductDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Name Uz */
      name_uz: string;
      /** Name Ru */
      name_ru?: string | null;
      /** Category Slug */
      category_slug: string;
      /** Brand Name */
      brand_name?: string | null;
      /** Oem Number */
      oem_number?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Rating Avg */
      rating_avg: string;
      /** Rating Count */
      rating_count: number;
      /** Sold Count */
      sold_count: number;
      best_offer: components["schemas"]["OfferOut"];
      /** Offer Count */
      offer_count: number;
      compatibility?: components["schemas"]["CompatibilityOut"] | null;
      /** Description Uz */
      description_uz?: string | null;
      /** Description Ru */
      description_ru?: string | null;
      /** Country Of Origin */
      country_of_origin?: string | null;
      /** Warranty Months */
      warranty_months?: number | null;
      status: components["schemas"]["ProductStatus"];
      /**
       * Oem Numbers
       * @default []
       */
      oem_numbers: string[];
      /**
       * Media
       * @default []
       */
      media: components["schemas"]["MediaOut"][];
      /**
       * Specs
       * @default []
       */
      specs: components["schemas"]["SpecOut"][];
      /**
       * Offers
       * @default []
       */
      offers: components["schemas"]["OfferOut"][];
      /**
       * Fits
       * @default []
       */
      fits: string[];
    };
    /** ProductListItem */
    ProductListItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Name Uz */
      name_uz: string;
      /** Name Ru */
      name_ru?: string | null;
      /** Category Slug */
      category_slug: string;
      /** Brand Name */
      brand_name?: string | null;
      /** Oem Number */
      oem_number?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Rating Avg */
      rating_avg: string;
      /** Rating Count */
      rating_count: number;
      /** Sold Count */
      sold_count: number;
      best_offer: components["schemas"]["OfferOut"];
      /** Offer Count */
      offer_count: number;
      compatibility?: components["schemas"]["CompatibilityOut"] | null;
    };
    /**
     * ProductStatus
     * @enum {string}
     */
    ProductStatus: "DRAFT" | "PENDING_REVIEW" | "ACTIVE" | "REJECTED" | "ARCHIVED";
    /** ProductUpdateIn */
    ProductUpdateIn: {
      /** Name Uz */
      name_uz?: string | null;
      /** Name Ru */
      name_ru?: string | null;
      /** Description Uz */
      description_uz?: string | null;
      /** Country Of Origin */
      country_of_origin?: string | null;
      /** Warranty Months */
      warranty_months?: number | null;
    };
    /** RefreshIn */
    RefreshIn: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** RegisterIn */
    RegisterIn: {
      /** Phone */
      phone?: string | null;
      /** Email */
      email?: string | null;
      /** Password */
      password: string;
      /** Full Name */
      full_name: string;
      /**
       * Locale
       * @default uz
       */
      locale: string;
    };
    /** SellerBrief */
    SellerBrief: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Store Name */
      store_name: string;
      /** District */
      district: string;
      /** Region */
      region: string;
      /** Rating Avg */
      rating_avg: string;
      /** Rating Count */
      rating_count: number;
      /** Verification Level */
      verification_level: string;
    };
    /** SellerOnboardIn */
    SellerOnboardIn: {
      /** Store Name */
      store_name: string;
      /** Region */
      region: string;
      /** District */
      district: string;
      /** Address */
      address?: string | null;
      /** Phone */
      phone?: string | null;
      /** Description Uz */
      description_uz?: string | null;
    };
    /** SellerOut */
    SellerOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Store Name */
      store_name: string;
      /** Logo Url */
      logo_url?: string | null;
      /** Description Uz */
      description_uz?: string | null;
      /** Region */
      region: string;
      /** District */
      district: string;
      /** Address */
      address?: string | null;
      /** Phone */
      phone?: string | null;
      status: components["schemas"]["SellerStatus"];
      verification_level: components["schemas"]["SellerVerificationLevel"];
      /** Rating Avg */
      rating_avg: string;
      /** Rating Count */
      rating_count: number;
      /** Sold Count */
      sold_count: number;
      /** Response Rate */
      response_rate: string;
      /** Working Hours */
      working_hours?: {
        [key: string]: unknown;
      } | null;
      /**
       * Product Count
       * @default 0
       */
      product_count: number;
    };
    /**
     * SellerStatus
     * @enum {string}
     */
    SellerStatus: "PENDING" | "ACTIVE" | "SUSPENDED" | "REJECTED";
    /** SellerUpdateIn */
    SellerUpdateIn: {
      /** Logo Url */
      logo_url?: string | null;
      /** Description Uz */
      description_uz?: string | null;
      /** Description Ru */
      description_ru?: string | null;
      /** Address */
      address?: string | null;
      /** Phone */
      phone?: string | null;
      /** Working Hours */
      working_hours?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * SellerVerificationLevel
     * @enum {string}
     */
    SellerVerificationLevel: "BASIC" | "BUSINESS_VERIFIED" | "TRUSTED_SELLER";
    /**
     * SortOrder
     * @enum {string}
     */
    SortOrder: "relevance" | "popular" | "price_asc" | "price_desc" | "rating" | "newest";
    /** SpecOut */
    SpecOut: {
      /** Label Uz */
      label_uz: string;
      /** Label Ru */
      label_ru?: string | null;
      /** Value */
      value: string;
    };
    /** StatusChangeIn */
    StatusChangeIn: {
      status: components["schemas"]["OrderStatus"];
      /** Note */
      note?: string | null;
    };
    /** SubOrderOut */
    SubOrderOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      status: components["schemas"]["OrderStatus"];
      /** Subtotal */
      subtotal: string;
      /** Delivery Fee */
      delivery_fee: string;
      delivery_method: components["schemas"]["DeliveryMethod"];
      seller: components["schemas"]["SellerBrief"];
      /** Items */
      items: components["schemas"]["OrderItemOut"][];
    };
    /** TokenPair */
    TokenPair: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      /**
       * Expires In
       * @default 900
       */
      expires_in: number;
    };
    /**
     * TransmissionType
     * @enum {string}
     */
    TransmissionType: "MANUAL" | "AUTOMATIC" | "ROBOT" | "CVT";
    /** UserOut */
    UserOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Phone */
      phone: string | null;
      /** Email */
      email: string | null;
      /** Full Name */
      full_name: string | null;
      /** Avatar Url */
      avatar_url: string | null;
      /** Locale */
      locale: string;
      /** Roles */
      roles: string[];
      /** Phone Verified */
      phone_verified: boolean;
      /** Email Verified */
      email_verified: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VariantOut */
    VariantOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Generation Id
       * Format: uuid
       */
      generation_id: string;
      /** Display Name */
      display_name: string;
      transmission: components["schemas"]["TransmissionType"];
      body_type: components["schemas"]["BodyType"];
      /** Year From */
      year_from: number;
      /** Year To */
      year_to?: number | null;
      /** Trim */
      trim?: string | null;
      engine?: components["schemas"]["EngineOut"] | null;
    };
    /** VerificationDecisionIn */
    VerificationDecisionIn: {
      /** Approved */
      approved: boolean;
      level?: components["schemas"]["SellerVerificationLevel"] | null;
      /** Reviewer Note */
      reviewer_note?: string | null;
    };
    /** VerificationRequestIn */
    VerificationRequestIn: {
      requested_level: components["schemas"]["SellerVerificationLevel"];
      /** Legal Name */
      legal_name?: string | null;
      /** Registration Number */
      registration_number?: string | null;
      /**
       * Document Urls
       * @default []
       */
      document_urls: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  register_api_v1_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  request_otp_api_v1_auth_otp_request_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OtpRequestIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OtpRequested"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  verify_otp_api_v1_auth_otp_verify_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OtpVerifyIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_all_api_v1_auth_logout_all_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  password_forgot_api_v1_auth_password_forgot_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordForgotIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OtpRequested"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  password_reset_api_v1_auth_password_reset_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  password_change_api_v1_auth_password_change_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordChangeIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
    };
  };
  list_brands_api_v1_vehicles_brands_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrandOut"][];
        };
      };
    };
  };
  list_models_api_v1_vehicles_brands__brand_slug__models_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        brand_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ModelOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_generations_api_v1_vehicles_models__model_id__generations_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        model_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenerationOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_years_api_v1_vehicles_models__model_id__years_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        model_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": number[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_variants_api_v1_vehicles_models__model_id__variants_get: {
    parameters: {
      query?: {
        year?: number | null;
      };
      header?: never;
      path: {
        model_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VariantOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_engines_api_v1_vehicles_engines_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EngineOut"][];
        };
      };
    };
  };
  list_vehicles_api_v1_garage_vehicles_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GarageVehicleOut"][];
        };
      };
    };
  };
  add_vehicle_api_v1_garage_vehicles_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GarageVehicleIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GarageVehicleOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_vehicle_api_v1_garage_vehicles__vehicle_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vehicle_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GarageVehicleOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_vehicle_api_v1_garage_vehicles__vehicle_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vehicle_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_vehicle_api_v1_garage_vehicles__vehicle_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vehicle_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GarageVehicleUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GarageVehicleOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  set_primary_api_v1_garage_vehicles__vehicle_id__primary_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vehicle_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GarageVehicleOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_categories_api_v1_catalog_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryOut"][];
        };
      };
    };
  };
  list_part_brands_api_v1_catalog_brands_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PartBrandOut"][];
        };
      };
    };
  };
  search_products_api_v1_products_get: {
    parameters: {
      query?: {
        /** @description Nom, OEM yoki artikul */
        q?: string | null;
        category?: string[] | null;
        brand?: string[] | null;
        seller_id?: string[] | null;
        price_min?: number | string | null;
        price_max?: number | string | null;
        rating_min?: number | string | null;
        in_stock?: boolean;
        warranty_min_months?: number | null;
        delivery_max_days?: number | null;
        /** @description Faqat mashinamga mos keladiganlar */
        fits_my_car?: boolean;
        /** @description Garajdagi mashina o'rniga */
        variant_id?: string | null;
        sort?: components["schemas"]["SortOrder"];
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_ProductListItem_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  suggest_api_v1_products_suggest_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  product_detail_api_v1_products__slug__get: {
    parameters: {
      query?: {
        variant_id?: string | null;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  check_api_v1_compatibility_check_get: {
    parameters: {
      query: {
        product_id: string;
        variant_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompatibilityOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  check_bulk_api_v1_compatibility_check_bulk_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompatibilityBulkQuery"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: components["schemas"]["CompatibilityOut"];
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upsert_claim_api_v1_compatibility_claims_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompatibilityClaimIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompatibilityOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  view_cart_api_v1_cart_get: {
    parameters: {
      query?: never;
      header?: {
        "x-cart-token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CartOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_item_api_v1_cart_items_post: {
    parameters: {
      query?: never;
      header?: {
        "x-cart-token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CartItemIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CartOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_item_api_v1_cart_items__item_id__delete: {
    parameters: {
      query?: never;
      header?: {
        "x-cart-token"?: string | null;
      };
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CartOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  set_quantity_api_v1_cart_items__item_id__patch: {
    parameters: {
      query?: never;
      header?: {
        "x-cart-token"?: string | null;
      };
      path: {
        item_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CartItemQuantityIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CartOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  merge_api_v1_cart_merge_post: {
    parameters: {
      query?: never;
      header?: {
        "x-cart-token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CartOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  checkout_api_v1_orders_checkout_post: {
    parameters: {
      query?: never;
      header?: {
        "x-cart-token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckoutIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_orders_api_v1_orders_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderOut"][];
        };
      };
    };
  };
  get_order_api_v1_orders__order_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_order_api_v1_orders__order_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StatusChangeIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  payment_callback_api_v1_payments_callback__provider__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  seller_orders_api_v1_seller__seller_id__orders_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        seller_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  seller_change_status_api_v1_seller__seller_id__orders__order_id__status_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        seller_id: string;
        order_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StatusChangeIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_sellers_api_v1_sellers_get: {
    parameters: {
      query?: {
        region?: string | null;
        district?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SellerOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_stores_api_v1_sellers_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SellerOut"][];
        };
      };
    };
  };
  seller_detail_api_v1_sellers__slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SellerOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  onboard_api_v1_sellers_onboard_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SellerOnboardIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SellerOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_store_api_v1_sellers__seller_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        seller_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SellerUpdateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SellerOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  request_verification_api_v1_sellers__seller_id__verification_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        seller_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerificationRequestIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  decide_verification_api_v1_sellers_verification__request_id__decide_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        request_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerificationDecisionIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_product_api_v1_seller__seller_id__products_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        seller_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductCreateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_product_api_v1_seller_products__product_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductUpdateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upsert_offer_api_v1_seller__seller_id__offers_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        seller_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OfferUpsertIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  ready_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
