/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as FeedVideoIdRouteImport } from './routes/feed.$videoId'
import { Route as GarageIndexRouteImport } from './routes/garage.index'
import { Route as GarageAddRouteImport } from './routes/garage.add'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as SellerAdsRouteImport } from './routes/seller.ads'
import { Route as SellerFeedRouteImport } from './routes/seller.feed'
import { Route as SellerFinanceRouteImport } from './routes/seller.finance'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerPromotionsRouteImport } from './routes/seller.promotions'
import { Route as SellerSettingsRouteImport } from './routes/seller.settings'
import { Route as SellerVideosRouteImport } from './routes/seller.videos'
import { Route as SellerWarehousesRouteImport } from './routes/seller.warehouses'
import { Route as SellerOnboardRouteImport } from './routes/seller_.onboard'
import { Route as FeedCreatorsHandleRouteImport } from './routes/feed.creators.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const FeedVideoIdRoute = FeedVideoIdRouteImport.update({
  id: '/$videoId',
  path: '/$videoId',
  getParentRoute: () => FeedRoute,
} as any)
const GarageIndexRoute = GarageIndexRouteImport.update({
  id: '/garage/',
  path: '/garage/',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageAddRoute = GarageAddRouteImport.update({
  id: '/garage/add',
  path: '/garage/add',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAdsRoute = SellerAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => SellerRoute,
} as any)
const SellerFeedRoute = SellerFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => SellerRoute,
} as any)
const SellerFinanceRoute = SellerFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SellerRoute,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerRoute,
} as any)
const SellerPromotionsRoute = SellerPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => SellerRoute,
} as any)
const SellerSettingsRoute = SellerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SellerRoute,
} as any)
const SellerVideosRoute = SellerVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => SellerRoute,
} as any)
const SellerWarehousesRoute = SellerWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => SellerRoute,
} as any)
const SellerOnboardRoute = SellerOnboardRouteImport.update({
  id: '/seller_/onboard',
  path: '/seller/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedCreatorsHandleRoute = FeedCreatorsHandleRouteImport.update({
  id: '/creators/$handle',
  path: '/creators/$handle',
  getParentRoute: () => FeedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/feed': typeof FeedRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/seller': typeof SellerRouteWithChildren
  '/wallet': typeof WalletRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/videos': typeof AdminVideosRoute
  '/feed/$videoId': typeof FeedVideoIdRoute
  '/garage/add': typeof GarageAddRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/ads': typeof SellerAdsRoute
  '/seller/feed': typeof SellerFeedRoute
  '/seller/finance': typeof SellerFinanceRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/promotions': typeof SellerPromotionsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/videos': typeof SellerVideosRoute
  '/seller/warehouses': typeof SellerWarehousesRoute
  '/seller/onboard': typeof SellerOnboardRoute
  '/admin/': typeof AdminIndexRoute
  '/garage/': typeof GarageIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/feed/creators/$handle': typeof FeedCreatorsHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/feed': typeof FeedRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/wallet': typeof WalletRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/videos': typeof AdminVideosRoute
  '/feed/$videoId': typeof FeedVideoIdRoute
  '/garage/add': typeof GarageAddRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/ads': typeof SellerAdsRoute
  '/seller/feed': typeof SellerFeedRoute
  '/seller/finance': typeof SellerFinanceRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/promotions': typeof SellerPromotionsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/videos': typeof SellerVideosRoute
  '/seller/warehouses': typeof SellerWarehousesRoute
  '/seller/onboard': typeof SellerOnboardRoute
  '/admin': typeof AdminIndexRoute
  '/garage': typeof GarageIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/seller': typeof SellerIndexRoute
  '/feed/creators/$handle': typeof FeedCreatorsHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/feed': typeof FeedRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/seller': typeof SellerRouteWithChildren
  '/wallet': typeof WalletRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/videos': typeof AdminVideosRoute
  '/feed/$videoId': typeof FeedVideoIdRoute
  '/garage/add': typeof GarageAddRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/ads': typeof SellerAdsRoute
  '/seller/feed': typeof SellerFeedRoute
  '/seller/finance': typeof SellerFinanceRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/promotions': typeof SellerPromotionsRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/videos': typeof SellerVideosRoute
  '/seller/warehouses': typeof SellerWarehousesRoute
  '/seller_/onboard': typeof SellerOnboardRoute
  '/admin/': typeof AdminIndexRoute
  '/garage/': typeof GarageIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/feed/creators/$handle': typeof FeedCreatorsHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/feed'
    | '/login'
    | '/marketplace'
    | '/profile'
    | '/register'
    | '/seller'
    | '/wallet'
    | '/admin/ads'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/promotions'
    | '/admin/sellers'
    | '/admin/system'
    | '/admin/videos'
    | '/feed/$videoId'
    | '/garage/add'
    | '/orders/$orderId'
    | '/product/$productId'
    | '/seller/ads'
    | '/seller/feed'
    | '/seller/finance'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/promotions'
    | '/seller/settings'
    | '/seller/videos'
    | '/seller/warehouses'
    | '/seller/onboard'
    | '/admin/'
    | '/garage/'
    | '/orders/'
    | '/seller/'
    | '/feed/creators/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/feed'
    | '/login'
    | '/marketplace'
    | '/profile'
    | '/register'
    | '/wallet'
    | '/admin/ads'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/promotions'
    | '/admin/sellers'
    | '/admin/system'
    | '/admin/videos'
    | '/feed/$videoId'
    | '/garage/add'
    | '/orders/$orderId'
    | '/product/$productId'
    | '/seller/ads'
    | '/seller/feed'
    | '/seller/finance'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/promotions'
    | '/seller/settings'
    | '/seller/videos'
    | '/seller/warehouses'
    | '/seller/onboard'
    | '/admin'
    | '/garage'
    | '/orders'
    | '/seller'
    | '/feed/creators/$handle'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/feed'
    | '/login'
    | '/marketplace'
    | '/profile'
    | '/register'
    | '/seller'
    | '/wallet'
    | '/admin/ads'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/promotions'
    | '/admin/sellers'
    | '/admin/system'
    | '/admin/videos'
    | '/feed/$videoId'
    | '/garage/add'
    | '/orders/$orderId'
    | '/product/$productId'
    | '/seller/ads'
    | '/seller/feed'
    | '/seller/finance'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/promotions'
    | '/seller/settings'
    | '/seller/videos'
    | '/seller/warehouses'
    | '/seller_/onboard'
    | '/admin/'
    | '/garage/'
    | '/orders/'
    | '/seller/'
    | '/feed/creators/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FeedRoute: typeof FeedRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SellerRoute: typeof SellerRouteWithChildren
  WalletRoute: typeof WalletRoute
  GarageAddRoute: typeof GarageAddRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  SellerOnboardRoute: typeof SellerOnboardRoute
  GarageIndexRoute: typeof GarageIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/feed/$videoId': {
      id: '/feed/$videoId'
      path: '/$videoId'
      fullPath: '/feed/$videoId'
      preLoaderRoute: typeof FeedVideoIdRouteImport
      parentRoute: typeof FeedRoute
    }
    '/garage/': {
      id: '/garage/'
      path: '/garage'
      fullPath: '/garage/'
      preLoaderRoute: typeof GarageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/add': {
      id: '/garage/add'
      path: '/garage/add'
      fullPath: '/garage/add'
      preLoaderRoute: typeof GarageAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/ads': {
      id: '/seller/ads'
      path: '/ads'
      fullPath: '/seller/ads'
      preLoaderRoute: typeof SellerAdsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/feed': {
      id: '/seller/feed'
      path: '/feed'
      fullPath: '/seller/feed'
      preLoaderRoute: typeof SellerFeedRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/finance': {
      id: '/seller/finance'
      path: '/finance'
      fullPath: '/seller/finance'
      preLoaderRoute: typeof SellerFinanceRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/promotions': {
      id: '/seller/promotions'
      path: '/promotions'
      fullPath: '/seller/promotions'
      preLoaderRoute: typeof SellerPromotionsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/settings': {
      id: '/seller/settings'
      path: '/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof SellerSettingsRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/videos': {
      id: '/seller/videos'
      path: '/videos'
      fullPath: '/seller/videos'
      preLoaderRoute: typeof SellerVideosRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/warehouses': {
      id: '/seller/warehouses'
      path: '/warehouses'
      fullPath: '/seller/warehouses'
      preLoaderRoute: typeof SellerWarehousesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller_/onboard': {
      id: '/seller_/onboard'
      path: '/seller/onboard'
      fullPath: '/seller/onboard'
      preLoaderRoute: typeof SellerOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/creators/$handle': {
      id: '/feed/creators/$handle'
      path: '/creators/$handle'
      fullPath: '/feed/creators/$handle'
      preLoaderRoute: typeof FeedCreatorsHandleRouteImport
      parentRoute: typeof FeedRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FeedRouteChildren {
  FeedVideoIdRoute: typeof FeedVideoIdRoute
  FeedCreatorsHandleRoute: typeof FeedCreatorsHandleRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedVideoIdRoute: FeedVideoIdRoute,
  FeedCreatorsHandleRoute: FeedCreatorsHandleRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

interface SellerRouteChildren {
  SellerAdsRoute: typeof SellerAdsRoute
  SellerFeedRoute: typeof SellerFeedRoute
  SellerFinanceRoute: typeof SellerFinanceRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerPromotionsRoute: typeof SellerPromotionsRoute
  SellerSettingsRoute: typeof SellerSettingsRoute
  SellerVideosRoute: typeof SellerVideosRoute
  SellerWarehousesRoute: typeof SellerWarehousesRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerAdsRoute: SellerAdsRoute,
  SellerFeedRoute: SellerFeedRoute,
  SellerFinanceRoute: SellerFinanceRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerPromotionsRoute: SellerPromotionsRoute,
  SellerSettingsRoute: SellerSettingsRoute,
  SellerVideosRoute: SellerVideosRoute,
  SellerWarehousesRoute: SellerWarehousesRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FeedRoute: FeedRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SellerRoute: SellerRouteWithChildren,
  WalletRoute: WalletRoute,
  GarageAddRoute: GarageAddRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  SellerOnboardRoute: SellerOnboardRoute,
  GarageIndexRoute: GarageIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
