/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as GarageIndexRouteImport } from './routes/garage.index'
import { Route as GarageAddRouteImport } from './routes/garage.add'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageIndexRoute = GarageIndexRouteImport.update({
  id: '/garage/',
  path: '/garage/',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageAddRoute = GarageAddRouteImport.update({
  id: '/garage/add',
  path: '/garage/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/marketplace': typeof MarketplaceRoute
  '/garage/add': typeof GarageAddRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/garage/': typeof GarageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/marketplace': typeof MarketplaceRoute
  '/garage/add': typeof GarageAddRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/garage': typeof GarageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/marketplace': typeof MarketplaceRoute
  '/garage/add': typeof GarageAddRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/garage/': typeof GarageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/marketplace'
    | '/garage/add'
    | '/product/$productId'
    | '/garage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/marketplace'
    | '/garage/add'
    | '/product/$productId'
    | '/garage'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/marketplace'
    | '/garage/add'
    | '/product/$productId'
    | '/garage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  MarketplaceRoute: typeof MarketplaceRoute
  GarageAddRoute: typeof GarageAddRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  GarageIndexRoute: typeof GarageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/': {
      id: '/garage/'
      path: '/garage'
      fullPath: '/garage/'
      preLoaderRoute: typeof GarageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/add': {
      id: '/garage/add'
      path: '/garage/add'
      fullPath: '/garage/add'
      preLoaderRoute: typeof GarageAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  MarketplaceRoute: MarketplaceRoute,
  GarageAddRoute: GarageAddRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  GarageIndexRoute: GarageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
